apiVersion: v1
kind: ConfigMap
metadata:
  name: theratime-config
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"

